service: default
runtime: python37

basic_scaling:
    max_instances: 5
    idle_timeout: 5m

resources:
  cpu: 30
  memory_gb: 30
  disk_size_gb: 1024
  
entrypoint: gunicorn -b 0.0.0.0:8080 main:server
